shared:
  settings:
    email:
      addresses: [kraune@verizonmedia.com]
      statuses: [SUCCESS, FAILURE]

jobs:
  link-checker-sample-apps:
    requires: [~pr, ~commit]
    image: ruby:2.6
    environment:
      USER_SHELL_BIN: bash
    steps:
      - install: |
          gem install bundler
          export LANG=C.UTF-8
          bundle install
      - add-front-matter-and-build: |
          find . -not -path './_site/*' -name README.md | while read f; do (echo -e "---\n---\n"; cat ${f})>${f}.new; mv ${f}.new ${f}; done
          for f in \
            msmarco-ranking/passage-ranking.md \
            msmarco-ranking/document-ranking.md \
            msmarco-ranking/colbert-performance-scaling.md \
            vespa-cloud/cord-19-search/feeding.md \
            vespa-cloud/cord-19-search/experiment-yourself.md; \
            do (echo -e "---\n---\n"; cat ${f})>${f}.new; mv ${f}.new ${f}; done
          bundle exec jekyll build -p /dev/null
      - check-links: >
          bundle exec htmlproofer --assume-extension --empty-alt-ignore
          --directory-index-file README.html
          --url-ignore 'src/main/application/schemas/wiki.sd#L80,http://localhost:8080/site'
          --file-ignore '/tensor-playground/src/main/resources/playground/'
          ./_site

  build-apps:
    requires: [~pr, ~commit]
    image: vespaengine/vespa-pipeline
    steps:
      - build: |
          set -e
          source /etc/profile.d/jdk-env.sh
          mvn -V --batch-mode --no-snapshot-updates install

  verify-guides:
    requires: [~commit]
    secrets:
      - VESPA_TEAM_API_KEY
    image: vespaengine/vespa-pipeline
    environment:
      USER_SHELL_BIN: bash
      DOCKER_HOST: 'localhost:2375'
    annotations:
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
    steps:
      - install-deps: |
          source /etc/profile.d/jdk-env.sh
          yum install -y python36-pip
          python3 -m pip install -qqq --upgrade pip
          python3 -m pip install -qqq -r test/requirements.txt --user
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum install -y docker-ce docker-ce-cli containerd.io openssl yum-utils
      - run-tests: |
          export VESPA_TEAM_API_KEY
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config.yml
