apiVersion: v1
kind: ConfigMap
metadata:
  name: vespa-config
data:
  VESPA_CONFIGSERVERS: >-
    {{- $domain := printf "%s.%s.svc.cluster.local" .Values.headlessName .Release.Namespace  }}
    {{- $replicas := int .Values.serverReplicas }}
    {{- $serverList := list }}
    {{- range $i := until $replicas }}
    {{- $serverList = append $serverList (printf "vespa-configserver-%d.%s" $i $domain) }}
    {{- end }}
    {{ join "," $serverList }}
  VESPA_CONFIGSERVER_JVMARGS: "{{ .Values.serverJvmArgs }}"
  VESPA_CONFIGPROXY_JVMARGS: "{{ .Values.proxyJvmArgs }}"