name: "Setup Vespa CLI and dependencies"
description: "Install Vespa CLI and dependencies"

runs:
  using: "composite"
  steps:
    # - name: Setup Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 3.1
    #     bundler-cache: true

    - uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Install python dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -qqq -r test/requirements.txt --user
        python3 -m pip install -qqq pytest nbmake --user

    - name: Install Vespa CLI
      uses: vespa-engine/setup-vespa-cli-action@v1
