name: Free disk space
description: Frees some disk space on the runner.

runs:
  using: "composite"
  steps:
    - name: Remove Android library (~14GiB)
      shell: bash
      run: |
        sudo rm -rf /usr/local/lib/android|| true

    - name: Remove .Net runtime (~2.7GiB)
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet|| true

    - name: Remove misc large packages (~5.3GiB)
      shell: bash
      run: |
        sudo apt-get remove -yq --fix-missing --autoremove '^aspnetcore-.*'    || true
        sudo apt-get remove -yq --fix-missing --autoremove '^dotnet-.*'       || true
        sudo apt-get remove -yq --fix-missing --autoremove '^llvm-.*'         || true
        sudo apt-get remove -yq --fix-missing --autoremove '^mongodb-.*'      || true
        sudo apt-get remove -yq --fix-missing --autoremove '^google-cloud-*'   || true
        sudo apt-get remove -yq --fix-missing --autoremove php-common php-pear|| true
        sudo apt-get remove -yq --fix-missing --autoremove mysql-common       || true
        sudo apt-get remove -yq --fix-missing --autoremove azure-cli powershell mono-devel libgl1-mesa-dri|| true
        sudo apt-get remove -yq --fix-missing --autoremove google-chrome-stable firefox microsoft-edge-stable|| true
        sudo apt-get remove -yq --fix-missing --autoremove snapd|| true
        sudo apt-get autoremove -yq|| true
        sudo apt-get clean|| true

    - name: Remove Tool Cache (~5.9GiB)
      shell: bash
      run: |
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"|| true
