version: '3.8'

services:
  vespa:
    image: vespaengine/vespa
    ports:
      - "8080:8080"
      - "19071:19071"
    depends_on:
      - embedder
    networks:
      - vespa_net

  embedder:
    image: michaelf34/infinity
    ports:
      - "${PORT:-1337}:${PORT:-1337}"
    volumes:
      - ${CACHE_VOLUME:-./cache}:/app/.cache
    command: [
      "v2",
      "--engine", "optimum",
      "--model-id", "nomic-ai/modernbert-embed-base",
      #"--model-id", "${MODEL2}",
      "--port", "1337"
    ]
    networks:
      - vespa_net

networks:
  vespa_net:
    driver: bridge