# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa-feed-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vespa-feed-container
      name: vespa-internal
  serviceName: vespa-internal
  template:
    metadata:
      labels:
        app: vespa-feed-container
        name: vespa-internal
    spec:
      containers:
      - name: vespa-feed-container
        image: vespaengine/vespa
        args: ["services"]
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: vespa-config
        securityContext:
          runAsUser: 1000
        resources:
          requests:
            memory: "1.5G"
          limits:
            memory: "1.5G"
