# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

# Global Configuration for all Prometheus jobs
global:
  scrape_interval: 10s # Set the scrape interval to every 10 seconds. Default is every 1 minute.
  scrape_timeout: 10s # How long to wait for timeout. 5s timeout gives 95% success. 10s timeout gives 99% success.

# A scrape configuration for the job album-recommendation
scrape_configs:

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'album-recommendation'

    # Metrics in prometheus format are available here
    metrics_path: /prometheus/v1/values

    # Used for docker-compose internal network management
    static_configs:
      - targets: ['vespa:19092']
