{
 "title": "Yamas Lookalike Dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "INDEX: Total Number of UNIQUE Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "global unique documents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "unique docs" }
   ],
   "targets": [
    {
     "expr": "content_proton_documentdb_documents_total_last"
    }
   ]
  },
  { "title": "Quality of Service HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "QUERY: Quality of Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "request rate" }
   ],
   "targets": [
    { "expr": "queries_rate" }
   ]
  },
  {
   "title": "FEED: Quality Of Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "request rate" }
   ],
   "targets": [
    { "expr": "feed_operations_rate" }
   ]
  },
  {
   "title": "LATENCY: Vespa QUERY Latency 95p/99p/mean    \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\    LATENCY: Vespa FEED Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "95p (AVG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "latency (ms)" }
   ],
   "targets": [
    {
     "expr": "query_latency_95percentile{endpoint=\"vespa:8080\"}"
    }
   ]
  },
  {
   "title": "99p (AVG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "latency (ms)" }
   ],
   "targets": [
    {
     "expr": "query_latency_99percentile{endpoint=\"vespa:8080\"}"
    }
   ]
  },
  {
   "title": "mean",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "latency (ms)" }
   ],
   "targets": [
    {
     "expr": "query_latency_average{endpoint=\"vespa:8080\"}"
    }
   ]
  },
  {
   "title": "container feed latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "latency (ms)" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "THROUGHPUT: Vespa QUERY Requests \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\  THROUGHPUT: Vespa FEED Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "query requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "queries (qps)" }
   ],
   "targets": [
    {
     "expr": "queries_rate{endpoint=\"vespa:8080\"}"
    }
   ]
  },
  {
   "title": "searchnode put operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "ops/sec" }
   ],
   "targets": [
    {}
   ]
  },
  { "title": "TRAFFIC: HTTP Vs HTTPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "http feed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "traffic" }
   ]
  },
  {
   "title": "http search",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "traffic" }
   ]
  },
  {
   "title": "https feed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "traffic" }
   ]
  },
  {
   "title": "https search",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "traffic" }
   ]
  },
  {
   "title": "CONTAINER: HTTP Response Codes - 4xx / 5xx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "container http 4xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "/s" }
     ],
     "targets": [
      { "expr": "http_status_4xx_rate" }
     ]
    },
    {
     "title": "container http 5xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "http_status_5xx_rate" }
     ]
    }
   ]
  },
  {
   "title": "UTILIZATION: CPU (Max,%) \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ UTILIZATION: MEMORY, By Cluster (Max, %)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "cpu util (%)" }
   ],
   "targets": [
    { "expr": "cpu" }
   ]
  },
  {
   "title": "content",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "cpu util (%)" }
   ]
  },
  {
   "title": "container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "mem util (%)" }
   ],
   "targets": [
    { "expr": "sum(memory_virt) / 12000000000" }
   ]
  },
  {
   "title": "content",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "mem util (%)" }
   ]
  },
  {
   "title": "UTILIZATION: DISK SPACE - \"/\" And/or \"/Home\", By Cluster (Max, %) \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ UTILIZATION: HOST DISK Busy, By Cluster (Max, %)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }
  },
  {
   "title": "container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "util (%)" }
   ]
  },
  {
   "title": "content",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "util (%)" }
   ]
  },
  {
   "title": "container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "disk busy (%)" }
   ]
  },
  {
   "title": "content",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "disk busy (%)" }
   ],
   "targets": [
    {}
   ]
  }
 ]
}