{
 "title": "Vespa Basic Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Performance Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Feed Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "feed_operations_rate", "legendFormat": "Feed Operations / Second" }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "queries_rate", "legendFormat": "Queries / Second" }
   ]
  },
  {
   "title": "Total Documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "content_proton_documentdb_documents_total_last",
     "legendFormat": "Total Documents in Storage"
    }
   ]
  },
  {
   "title": "Query: Average Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "query_latency_average", "legendFormat": "Average Query Latency" }
   ]
  },
  {
   "title": "Query: 95 Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "query_latency_95percentile", "legendFormat": "95 Percentile Query Latency" }
   ]
  },
  {
   "title": "Query: 99 Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    { "expr": "query_latency_99percentile", "legendFormat": "99 Percentile Query Latency" }
   ]
  }
 ]
}