{
 "title": "Vespa Detailed Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Global Unique Documents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "unique docs" }
   ],
   "targets": [
    {
     "expr": "content_proton_documentdb_documents_total_last"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "request rate" }
   ],
   "targets": [
    { "expr": "queries_rate" }
   ]
  },
  {
   "title": "Feed Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "request rate" }
   ],
   "targets": [
    { "expr": "feed_operations_rate" }
   ]
  },
  {
   "title": "95p (AVG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "latency (ms)" }
   ],
   "targets": [
    { "expr": "query_latency_95percentile" }
   ]
  },
  {
   "title": "99p (AVG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "latency (ms)" }
   ],
   "targets": [
    { "expr": "query_latency_99percentile" }
   ]
  },
  {
   "title": "mean",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "latency (ms)" }
   ],
   "targets": [
    { "expr": "query_latency_average" }
   ]
  },
  {
   "title": "Http Status 200 Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "200 Rate" }
   ],
   "targets": [
    { "expr": "http_status_2xx_rate" }
   ]
  },
  {
   "title": "Http Status 4xx Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Responses Per Second" }
   ],
   "targets": [
    { "expr": "http_status_4xx_rate" }
   ]
  },
  {
   "title": "container http 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_status_5xx_rate" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "cpu util (%)" }
   ],
   "targets": [
    { "expr": "cpu" }
   ]
  },
  {
   "title": "Proton Document Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "content_proton_documentdb_disk_usage_last / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Proton Resource Disk Usage Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "disk usage (%)" }
   ],
   "targets": [
    {
     "expr": "content_proton_resource_usage_disk_average * 100"
    }
   ]
  },
  {
   "title": "Proton Memory Usage Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "mem util (%)" }
   ],
   "targets": [
    {
     "expr": "content_proton_resource_usage_memory_average * 100"
    }
   ]
  }
 ]
}