name: Verify Guides (Main)

on:
  workflow_dispatch: # Allow manual triggering of this workflow.

  push:
    branches: ["master"]
    paths-ignore:
      - "billion-scale-vector-search/"
      - "billion-scale-image-search/"
      - "examples/model-deployment/"
      - "field-generator/"
      - ".github/**"
      - Gemfile.lock
      - "!.github/workflows/verify-guides-main.yml"

jobs:
  main:
    uses: vespa-engine/gh-actions/.github/workflows/verify-markdown-guides.yml@main
    with:
      test-config-path: "test/_test_config.yml"
