name: Verify Giudes (Main)

on:
  workflow_dispatch: # Allow manual triggering of this workflow.

  push:
    branches: ["master"]
    paths-ignore:
      - "billion-scale-vector-search/"
      - "billion-scale-image-search/"
      - "examples/model-deployment/"

  pull_request:
    branches: ["master"]
    paths-ignore:
      - "billion-scale-vector-search/"
      - "billion-scale-image-search/"
      - "examples/model-deployment/"

jobs:
  main:
    uses: vespa-engine/gh-actions/.github/workflows/verify-markdown-guides.yml@verify-markdown-guides
    with:
      test-config-path: "test/_test_config.yml"
